# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bc99656ff6ae57db8d5b9d0ffc3d4a30e89609a280ca10a11679663ebaa2c9d133980098035cc280a5938adccf64a2a9e91ac66ad085ad3cf6c9b83f948b406

test:
  secret_key_base: 47b0107646bf7ed4b70e2cad65659c820aa7a66a790b68660f0c786130d4bc5bd14e152ac0c43478d102b88d8d440fc10b1d93bc5541288e6dbc4eb5d7908ed1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
